### ISSUE TITLE
two-way binding on embed-data

### ISSUE THREAD

**Issue by rkimaoui** [ritz078/ngEmbed#23]
Hello there,

How can i make a two-way binding on embed-data ?
I want to reload the directive everytime embed-data change.

At the moment when i bind with a ng-model, i get this error:

`javascript  TypeError: Cannot read property 'replace' of undefined
    at Object.codeProcess.getCode (http://localhost:3000/bower_components/ngEmbed/src/ng-embed.js:596:40)
    at link (http://localhost:3000/bower_components/ngEmbed/src/ng-embed.js:757:48)
    at invokeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8789:9)
    at nodeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8289:11)
    at http://localhost:3000/bower_components/angular/angular.js:8519:13
    at processQueue (http://localhost:3000/bower_components/angular/angular.js:14745:28)
    at http://localhost:3000/bower_components/angular/angular.js:14761:27
    at Scope.$eval (http://localhost:3000/bower_components/angular/angular.js:15989:28)
    at Scope.$digest (http://localhost:3000/bower_components/angular/angular.js:15800:31)
    at Scope.scopePrototype.$digest (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1972:23) <ng-embed data-embed-data="{{vm.post.content}}" embed-options="vm.options" embed-template-url="/app/spaces/embed-template.tmpl.html" class="ng-scope">`

Thanks in advance.
Reda

**Comment by ritz078** [comment]
Two way data binding is already present . Can you create a demo on plunker or codepen ?

**Comment by rkimaoui** [comment]
Ok i'll create a demo on codepen.

**Comment by leosuncin** [comment]
Only update if you use as filter, but can't embed video, audio, etc. just emoticons and links
http://embed.plnkr.co/PMV804/
In create post view after the editor, you can see the behavior of directive and filter

**Comment by leosuncin** [comment]
Maybe you can add a `scope.$watch` inside directive function to solve it
